<?php

namespace LLPP\MyTestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArchivioProdottiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivioProdottiRepository extends EntityRepository
{
}
