LLPP\MyTestBundle\Entity\AggiornamentiPrezziPerIva2128092011:
    type: entity
    table: aggiornamenti_prezzi_per_iva_21_28092011
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        isbn:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: ISBN
        prezzoNuovo:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: prezzo_nuovo
    lifecycleCallbacks: {  }
