LLPP\MyTestBundle\Entity\ArchivioAziendaApprofondimento:
    type: entity
    table: archivio_azienda_approfondimento
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        idazienda:
            type: integer
            nullable: true
            unsigned: false
            column: idAzienda
        testoapprofondimento:
            type: text
            nullable: false
            length: null
            fixed: false
            column: testoApprofondimento
        bannerinfo:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: bannerInfo
        linkbannerinfo:
            type: text
            nullable: true
            length: 255
            fixed: false
            column: linkbannerInfo
        testopostinvio:
            type: text
            nullable: true
            length: 65535
            fixed: false
            column: testoPostInvio
        linkpostinvio:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: linkPostInvio
    lifecycleCallbacks: {  }
