LLPP\MyTestBundle\Entity\ArchivioProdottiOpzioni:
    type: entity
    table: archivio_prodotti_opzioni
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: true
            length: 255
            fixed: false
        testo:
            type: text
            nullable: true
            length: 65535
            fixed: false
        idazienda:
            type: integer
            nullable: true
            unsigned: false
            column: idAzienda
        attivo:
            type: string
            nullable: false
            length: null
            fixed: false
            default: SI
        valorecheck:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: valoreCheck
        img50x50:
            type: string
            nullable: true
            length: 255
            fixed: false
        idapprofondimento:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: idApprofondimento
    lifecycleCallbacks: {  }
