LLPP\MyTestBundle\Entity\Banner:
    type: entity
    table: banner
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idazienda:
            type: integer
            nullable: true
            unsigned: false
            column: idAzienda
        azienda:
            type: string
            nullable: true
            length: 200
            fixed: false
        oggetto:
            type: text
            nullable: true
            length: 65535
            fixed: false
        tipo:
            type: string
            nullable: true
            length: null
            fixed: false
        posizione:
            type: string
            nullable: true
            length: null
            fixed: false
        tipocampagna:
            type: string
            nullable: false
            length: null
            fixed: false
            default: SCADENZA
            column: tipoCampagna
        datainizio:
            type: date
            nullable: true
            column: dataInizio
        datafine:
            type: date
            nullable: true
            column: dataFine
        file:
            type: string
            nullable: true
            length: 200
            fixed: false
        link:
            type: string
            nullable: true
            length: 200
            fixed: false
        widthswf:
            type: integer
            nullable: true
            unsigned: false
            column: widthSWF
        heightswf:
            type: integer
            nullable: true
            unsigned: false
            column: heightSWF
        idvideo:
            type: integer
            nullable: true
            unsigned: false
            column: idVideo
        statisticheattive:
            type: string
            nullable: false
            length: null
            fixed: false
            default: NO
            column: statisticheAttive
        codiceconteggio:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: codiceConteggio
        impressioncampagna:
            type: integer
            nullable: true
            unsigned: false
            column: impressionCampagna
        impression:
            type: integer
            nullable: false
            unsigned: false
        contatore:
            type: integer
            nullable: false
            unsigned: false
    lifecycleCallbacks: {  }
