LLPP\MyTestBundle\Entity\BannerNewsletter2:
    type: entity
    table: banner_newsletter2
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descrizione:
            type: string
            nullable: false
            length: 20
            fixed: true
        file:
            type: string
            nullable: false
            length: 100
            fixed: true
    lifecycleCallbacks: {  }
