LLPP\MyTestBundle\Entity\Blacklist:
    type: entity
    table: blacklist
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        indirizzo:
            type: string
            nullable: true
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
