LLPP\MyTestBundle\Entity\BoxLibriNews:
    type: entity
    table: box_libri_news
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        isbn:
            type: string
            nullable: false
            length: 90
            fixed: false
            default: ''
    lifecycleCallbacks: {  }
