LLPP\MyTestBundle\Entity\Carrello:
    type: entity
    table: carrello
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        sessione:
            type: string
            nullable: true
            length: 200
            fixed: false
        codice:
            type: string
            nullable: true
            length: 200
            fixed: false
        qta:
            type: integer
            nullable: true
            unsigned: false
        prezzo:
            type: float
            nullable: true
            precision: 5
            scale: 2
        spese:
            type: float
            nullable: true
            precision: 5
            scale: 2
        totaleRigo:
            type: float
            nullable: true
            precision: 5
            scale: 2
            column: totale_rigo
        ts:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
    lifecycleCallbacks: {  }
