LLPP\MyTestBundle\Entity\CategorieAziende:
    type: entity
    table: categorie_aziende
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        categoria:
            type: text
            nullable: true
            length: 65535
            fixed: false
        sottocategoria:
            type: text
            nullable: true
            length: 65535
            fixed: false
    lifecycleCallbacks: {  }
