LLPP\MyTestBundle\Entity\CertificazioniAziende:
    type: entity
    table: certificazioni_aziende
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idAzienda:
            type: integer
            nullable: true
            unsigned: false
            column: id_azienda
        nomeAzienda:
            type: string
            nullable: true
            length: 200
            fixed: false
            column: nome_azienda
        idCertificazione:
            type: integer
            nullable: true
            unsigned: false
            column: id_certificazione
        nomeCertificazione:
            type: string
            nullable: true
            length: 200
            fixed: false
            column: nome_certificazione
    lifecycleCallbacks: {  }
