LLPP\MyTestBundle\Entity\CommentiBook:
    type: entity
    table: commenti_book
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: true
            length: 120
            fixed: false
        titolo:
            type: text
            nullable: true
            length: 65535
            fixed: false
        commento:
            type: text
            nullable: true
            length: 65535
            fixed: false
        isbn:
            type: string
            nullable: true
            length: 20
            fixed: false
        voto:
            type: string
            nullable: true
            length: 1
            fixed: true
        data:
            type: date
            nullable: true
        approvato:
            type: string
            nullable: false
            length: null
            fixed: false
            default: NO
    lifecycleCallbacks: {  }
