LLPP\MyTestBundle\Entity\CvsQuery:
    type: entity
    table: cvs_query
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: true
            length: 50
            fixed: false
        query:
            type: text
            nullable: true
            length: 65535
            fixed: false
    lifecycleCallbacks: {  }
