LLPP\MyTestBundle\Entity\Editori:
    type: entity
    table: editori
    id:
        codice:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: Codice
            generator:
                strategy: IDENTITY
    fields:
        denominazione:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: Denominazione
    lifecycleCallbacks: {  }
