LLPP\MyTestBundle\Entity\ElencoArgomenti:
    type: entity
    table: elenco_argomenti
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nomeArgomento:
            type: string
            nullable: true
            length: 200
            fixed: false
            column: nome_argomento
    lifecycleCallbacks: {  }
