LLPP\MyTestBundle\Entity\ExportNewsletter:
    type: entity
    table: export_newsletter
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        indirizzo:
            type: string
            nullable: true
            length: 250
            fixed: false
        nominativo:
            type: string
            nullable: true
            length: 250
            fixed: false
    lifecycleCallbacks: {  }
