LLPP\MyTestBundle\Entity\Gazzettesicilia:
    type: entity
    table: gazzetteSicilia
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        titolo:
            type: string
            nullable: true
            length: 255
            fixed: false
        data:
            type: date
            nullable: true
        link:
            type: string
            nullable: true
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
