LLPP\MyTestBundle\Entity\ImpostazioniNewsletter:
    type: entity
    table: impostazioni_newsletter
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        oggetto:
            type: string
            nullable: false
            length: 250
            fixed: false
            default: ''
        testo:
            type: text
            nullable: false
            length: null
            fixed: false
        data:
            type: string
            nullable: false
            length: 12
            fixed: false
            default: ''
    lifecycleCallbacks: {  }
