LLPP\MyTestBundle\Entity\Inventario:
    type: entity
    table: inventario
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        codice:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: CODICE
        qta:
            type: integer
            nullable: true
            unsigned: false
            column: QTA
    lifecycleCallbacks: {  }
