LLPP\MyTestBundle\Entity\LibreriaSpessoCompratiAssieme:
    type: entity
    table: libreria_spesso_comprati_assieme
    uniqueConstraints:
        isbn:
            columns:
                - isbn
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        isbn:
            type: string
            nullable: false
            length: 255
            fixed: false
        listaCorrelati:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: 'Inserire i vari isbn separati da virgola SENZA spazio'
            column: lista_correlati
    lifecycleCallbacks: {  }
