LLPP\MyTestBundle\Entity\ListaNeraBackup:
    type: entity
    table: lista_nera_backup
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        indirizzo:
            type: string
            nullable: true
            length: 200
            fixed: false
        dataInserimento:
            type: string
            nullable: true
            length: 30
            fixed: false
            column: data_inserimento
    lifecycleCallbacks: {  }
