LLPP\MyTestBundle\Entity\LlppEmail:
    type: entity
    table: llpp_email
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        sezione:
            type: string
            nullable: false
            length: 255
            fixed: false
        spiegazione:
            type: text
            nullable: false
            length: 65535
            fixed: false
        da:
            type: string
            nullable: true
            length: 255
            fixed: false
        nomeMittente:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: nome_mittente
        html:
            type: text
            nullable: false
            length: 65535
            fixed: false
        oggetto:
            type: string
            nullable: false
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
