LLPP\MyTestBundle\Entity\Llppabbonati:
    type: entity
    table: LLPPAbbonati
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        idcliente:
            type: integer
            nullable: true
            unsigned: false
            column: idCliente
        datascadenza:
            type: date
            nullable: false
            column: dataScadenza
        nome:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: Nome
        cognome:
            type: string
            nullable: true
            length: 60
            fixed: false
            column: Cognome
        email:
            type: string
            nullable: true
            length: 80
            fixed: false
            column: Email
    lifecycleCallbacks: {  }
