LLPP\MyTestBundle\Entity\LlPpNumeri:
    type: entity
    table: ll_pp_numeri
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        codice:
            type: string
            nullable: false
            length: 60
            fixed: false
            default: ''
        img:
            type: string
            nullable: false
            length: 80
            fixed: false
            default: ''
        anno:
            type: string
            nullable: false
            length: 20
            fixed: false
            default: ''
        mese:
            type: string
            nullable: false
            length: 10
            fixed: false
            default: ''
        oggetto:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: ''
        pdf:
            type: string
            nullable: false
            length: 80
            fixed: false
            default: ''
        pacchetti:
            type: string
            nullable: true
            length: 255
            fixed: false
        banner:
            type: text
            nullable: true
            length: 65535
            fixed: false
        descrizione:
            type: text
            nullable: true
            length: 65535
            fixed: false
    lifecycleCallbacks: {  }
