LLPP\MyTestBundle\Entity\Lnblocchicad:
    type: entity
    table: lnBlocchiCAD
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        idCliente:
            type: integer
            nullable: true
            unsigned: false
            column: id_cliente
        categoria:
            type: string
            nullable: true
            length: 60
            fixed: false
        titolo:
            type: string
            nullable: true
            length: 255
            fixed: false
        descrizione:
            type: text
            nullable: true
            length: 65535
            fixed: false
        imganteprima:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: imgAnteprima
        bloccocad:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: bloccoCAD
        data:
            type: date
            nullable: true
    lifecycleCallbacks: {  }
