LLPP\MyTestBundle\Entity\Lntopmenu:
    type: entity
    table: lnTopMenu
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        testo:
            type: string
            nullable: true
            length: 255
            fixed: false
        ordine:
            type: integer
            nullable: true
            unsigned: false
        link:
            type: string
            nullable: true
            length: 80
            fixed: false
    lifecycleCallbacks: {  }
