LLPP\MyTestBundle\Entity\PhpbbRanks:
    type: entity
    table: phpbb_ranks
    id:
        rankId:
            type: smallint
            nullable: false
            unsigned: true
            id: true
            column: rank_id
            generator:
                strategy: IDENTITY
    fields:
        rankTitle:
            type: string
            nullable: false
            length: 50
            fixed: false
            default: ''
            column: rank_title
        rankMin:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: rank_min
        rankSpecial:
            type: boolean
            nullable: true
            default: '0'
            column: rank_special
        rankImage:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: rank_image
    lifecycleCallbacks: {  }
