LLPP\MyTestBundle\Entity\PhpbbBanlist:
    type: entity
    table: phpbb_banlist
    indexes:
        ban_ip_user_id:
            columns:
                - ban_ip
                - ban_userid
    id:
        banId:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: ban_id
            generator:
                strategy: IDENTITY
    fields:
        banUserid:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: ban_userid
        banIp:
            type: string
            nullable: false
            length: 8
            fixed: false
            default: ''
            column: ban_ip
        banEmail:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: ban_email
    lifecycleCallbacks: {  }
