LLPP\MyTestBundle\Entity\PhpbbConfig:
    type: entity
    table: phpbb_config
    id:
        configName:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: ''
            id: true
            column: config_name
            generator:
                strategy: IDENTITY
    fields:
        configValue:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: ''
            column: config_value
    lifecycleCallbacks: {  }
