LLPP\MyTestBundle\Entity\PhpbbTopics:
    type: entity
    table: phpbb_topics
    indexes:
        forum_id:
            columns:
                - forum_id
        topic_moved_id:
            columns:
                - topic_moved_id
        topic_status:
            columns:
                - topic_status
        topic_type:
            columns:
                - topic_type
    id:
        topicId:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: topic_id
            generator:
                strategy: IDENTITY
    fields:
        forumId:
            type: smallint
            nullable: false
            unsigned: true
            default: '0'
            column: forum_id
        topicTitle:
            type: string
            nullable: false
            length: 60
            fixed: true
            default: ''
            column: topic_title
        topicPoster:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: topic_poster
        topicTime:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: topic_time
        topicViews:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
            column: topic_views
        topicReplies:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
            column: topic_replies
        topicStatus:
            type: boolean
            nullable: false
            default: '0'
            column: topic_status
        topicVote:
            type: boolean
            nullable: false
            default: '0'
            column: topic_vote
        topicType:
            type: boolean
            nullable: false
            default: '0'
            column: topic_type
        topicFirstPostId:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
            column: topic_first_post_id
        topicLastPostId:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
            column: topic_last_post_id
        topicMovedId:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
            column: topic_moved_id
    lifecycleCallbacks: {  }
