LLPP\MyTestBundle\Entity\PostBlogger:
    type: entity
    table: post_blogger
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        data:
            type: date
            nullable: true
        user:
            type: string
            nullable: true
            length: 255
            fixed: false
        titolo:
            type: text
            nullable: true
            length: 65535
            fixed: false
        content:
            type: text
            nullable: true
            length: 65535
            fixed: false
    lifecycleCallbacks: {  }
