LLPP\MyTestBundle\Entity\Professioni:
    type: entity
    table: professioni
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        professione:
            type: string
            nullable: true
            length: 40
            fixed: false
    lifecycleCallbacks: {  }
