LLPP\MyTestBundle\Entity\QueryRicercaNotizie:
    type: entity
    table: query_ricerca_notizie
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        sessione:
            type: string
            nullable: true
            length: 60
            fixed: false
        query:
            type: string
            nullable: true
            length: 250
            fixed: false
        testo:
            type: string
            nullable: true
            length: 200
            fixed: false
        ts:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
    lifecycleCallbacks: {  }
