LLPP\MyTestBundle\Entity\Searchtag:
    type: entity
    table: searchTag
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        testo:
            type: string
            nullable: true
            length: 255
            fixed: false
        data:
            type: datetime
            nullable: true
        utente:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: Anonimo
    lifecycleCallbacks: {  }
