LLPP\MyTestBundle\Entity\SegnalazioneindirizzicniTest:
    type: entity
    table: segnalazioneIndirizziCNI_test
    id:
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nominativo:
            type: string
            nullable: false
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
