LLPP\MyTestBundle\Entity\Segnalazionilink:
    type: entity
    table: segnalazioniLink
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        mittente:
            type: string
            nullable: true
            length: 255
            fixed: false
        mittenteemail:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: mittenteEmail
        destinatario:
            type: text
            nullable: true
            length: 65535
            fixed: false
        destinatarioemail:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: destinatarioEmail
        testo:
            type: text
            nullable: true
            length: 65535
            fixed: false
        data:
            type: datetime
            nullable: true
        link:
            type: text
            nullable: true
            length: 65535
            fixed: false
    lifecycleCallbacks: {  }
