LLPP\MyTestBundle\Entity\Sondaggiconcorsi:
    type: entity
    table: sondaggiConcorsi
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        titolo:
            type: text
            nullable: true
            length: 65535
            fixed: false
        tipoconcorso:
            type: string
            nullable: true
            length: null
            fixed: false
            column: tipoConcorso
        mail:
            type: text
            nullable: true
            length: 65535
            fixed: false
    lifecycleCallbacks: {  }
