LLPP\MyTestBundle\Entity\Sondaggicommenti:
    type: entity
    table: sondaggiCommenti
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        idSondaggio:
            type: integer
            nullable: true
            unsigned: false
            column: id_sondaggio
        titolo:
            type: string
            nullable: true
            length: 255
            fixed: false
        testo:
            type: text
            nullable: true
            length: 65535
            fixed: false
        approvato:
            type: string
            nullable: true
            length: null
            fixed: false
            default: NO
        ok:
            type: integer
            nullable: false
            unsigned: false
        no:
            type: integer
            nullable: false
            unsigned: false
        titolocommento:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: titoloCommento
        data:
            type: date
            nullable: true
        orario:
            type: time
            nullable: true
        ip:
            type: string
            nullable: true
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
