LLPP\MyTestBundle\Entity\TabellaA:
    type: entity
    table: tabella_A
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        classecategoria:
            type: string
            nullable: true
            length: 5
            fixed: true
            column: CLASSECATEGORIA
        n:
            type: float
            nullable: true
            precision: 16
            scale: 9
            column: N
        q:
            type: float
            nullable: true
            precision: 16
            scale: 9
            column: Q
        x3:
            type: float
            nullable: true
            precision: 16
            scale: 9
            column: X3
    lifecycleCallbacks: {  }
