LLPP\MyTestBundle\Entity\Tblindirizzipersegnalazione:
    type: entity
    table: tblIndirizziPerSegnalazione
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        nomedestinatario:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: nomeDestinatario
        email:
            type: string
            nullable: true
            length: 255
            fixed: false
        testo:
            type: text
            nullable: true
            length: 65535
            fixed: false
    lifecycleCallbacks: {  }
