<?php

namespace LLPP\JournalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends EntityRepository
{
	public function getOneByNameLike($string)
	{
		$string = '%' . strtoupper($string) . '%';
	
		return $this->createQueryBuilder('c')
			->add('where', 'upper(c.nome) LIKE :string')
			->setParameter('search', $string)
			->getQuery()
			->getResult();
	}
}
