<?php

namespace LLPP\JournalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CorsoFormazioneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorsoFormazioneRepository extends EntityRepository
{
}
