<?php

namespace Grafill\ManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieArticoliRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieArticoliRepository extends EntityRepository
{
}
